project_id = "suxbqdcnidvdfmkrshem"

[functions.create-payment-session]
verify_jwt = true

[functions.verify-payment-session]
verify_jwt = true

[functions.fetch-series]
verify_jwt = true

[functions.og-image]
verify_jwt = false

[functions.telegram-auto-post]
verify_jwt = false

[functions.telegram-box-office]
verify_jwt = false

[functions.setup-cron]
verify_jwt = false

[functions.bridge-download]
verify_jwt = true

[functions.phono-search]
verify_jwt = false
